App:
  Host: localhost
  Port: 8080
Mysql:
  Host: localhost
  Port: 3306
  User: root
  Password: root
  DBName: nftswap
Redis:
  Host: localhost
  Port: 6379
  Password: ""
  DB: 0
Rabbitmq:
  Host: localhost
  Port: 5672
  Username: guest
  Password: guest
  Vhost: /
